baseurl = "https://www.eveguide.cn/"
title = "EVE新玩家指南"
languageCode = "zh-cn"

theme = "hugo-themes-learn"
publishdir = "public"
builddrafts = true

[params]
  editURL = ""
  author = "watch eagle"
  disableLandingPageButton = true
  disableMermaid = true
  disableSearch = true
